name: splatam
channels:
  - nvidia/label/cuda-12.8.1
  - conda-forge
  - defaults
dependencies:
  - cuda-toolkit=12.8.1
  - python=3.10
#  - tqdm=4.65.0
#  - Pillow
#  - faiss-gpu
#  - opencv
#  - imageio
#  - matplotlib
#  - kornia
#  - natsort
#  - pyyaml
#  - wandb
#  - gxx_linux-64=10
  - pip=25.2
#  - pip:
#    - lpips
#    - open3d==0.16.0
#    - torchmetrics
#    - cyclonedds
#    - git+https://github.com/JonathonLuiten/diff-gaussian-rasterization-w-depth.git@cb65e4b86bc3bd8ed42174b72a62e8d3a3a71110
